/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterNetworkRouteImport } from './routes/recruiter.network'
import { Route as RecruiterFingerprintRouteImport } from './routes/recruiter.fingerprint'
import { Route as RecruiterDashboardRouteImport } from './routes/recruiter.dashboard'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateLoginRouteImport } from './routes/candidate.login'
import { Route as CandidateDataRouteImport } from './routes/candidate.data'
import { Route as CandidateConsentRouteImport } from './routes/candidate.consent'
import { Route as RecruiterReqNewRouteImport } from './routes/recruiter.req.new'
import { Route as RecruiterReqReqIdRouteImport } from './routes/recruiter.req.$reqId'
import { Route as RecruiterCandidateCandidateIdRouteImport } from './routes/recruiter.candidate.$candidateId'
import { Route as RecruiterReqReqIdRerankRouteImport } from './routes/recruiter.req.$reqId_.rerank'

const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterNetworkRoute = RecruiterNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterFingerprintRoute = RecruiterFingerprintRouteImport.update({
  id: '/fingerprint',
  path: '/fingerprint',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterDashboardRoute = RecruiterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RecruiterRoute,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateLoginRoute = CandidateLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateDataRoute = CandidateDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateConsentRoute = CandidateConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => CandidateRoute,
} as any)
const RecruiterReqNewRoute = RecruiterReqNewRouteImport.update({
  id: '/req/new',
  path: '/req/new',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterReqReqIdRoute = RecruiterReqReqIdRouteImport.update({
  id: '/req/$reqId',
  path: '/req/$reqId',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterCandidateCandidateIdRoute =
  RecruiterCandidateCandidateIdRouteImport.update({
    id: '/candidate/$candidateId',
    path: '/candidate/$candidateId',
    getParentRoute: () => RecruiterRoute,
  } as any)
const RecruiterReqReqIdRerankRoute = RecruiterReqReqIdRerankRouteImport.update({
  id: '/req/$reqId_/rerank',
  path: '/req/$reqId/rerank',
  getParentRoute: () => RecruiterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/recruiter': typeof RecruiterRouteWithChildren
  '/candidate/consent': typeof CandidateConsentRoute
  '/candidate/data': typeof CandidateDataRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/fingerprint': typeof RecruiterFingerprintRoute
  '/recruiter/network': typeof RecruiterNetworkRoute
  '/recruiter/candidate/$candidateId': typeof RecruiterCandidateCandidateIdRoute
  '/recruiter/req/$reqId': typeof RecruiterReqReqIdRoute
  '/recruiter/req/new': typeof RecruiterReqNewRoute
  '/recruiter/req/$reqId/rerank': typeof RecruiterReqReqIdRerankRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/recruiter': typeof RecruiterRouteWithChildren
  '/candidate/consent': typeof CandidateConsentRoute
  '/candidate/data': typeof CandidateDataRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/fingerprint': typeof RecruiterFingerprintRoute
  '/recruiter/network': typeof RecruiterNetworkRoute
  '/recruiter/candidate/$candidateId': typeof RecruiterCandidateCandidateIdRoute
  '/recruiter/req/$reqId': typeof RecruiterReqReqIdRoute
  '/recruiter/req/new': typeof RecruiterReqNewRoute
  '/recruiter/req/$reqId/rerank': typeof RecruiterReqReqIdRerankRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/recruiter': typeof RecruiterRouteWithChildren
  '/candidate/consent': typeof CandidateConsentRoute
  '/candidate/data': typeof CandidateDataRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/fingerprint': typeof RecruiterFingerprintRoute
  '/recruiter/network': typeof RecruiterNetworkRoute
  '/recruiter/candidate/$candidateId': typeof RecruiterCandidateCandidateIdRoute
  '/recruiter/req/$reqId': typeof RecruiterReqReqIdRoute
  '/recruiter/req/new': typeof RecruiterReqNewRoute
  '/recruiter/req/$reqId_/rerank': typeof RecruiterReqReqIdRerankRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidate'
    | '/recruiter'
    | '/candidate/consent'
    | '/candidate/data'
    | '/candidate/login'
    | '/candidate/profile'
    | '/recruiter/dashboard'
    | '/recruiter/fingerprint'
    | '/recruiter/network'
    | '/recruiter/candidate/$candidateId'
    | '/recruiter/req/$reqId'
    | '/recruiter/req/new'
    | '/recruiter/req/$reqId/rerank'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidate'
    | '/recruiter'
    | '/candidate/consent'
    | '/candidate/data'
    | '/candidate/login'
    | '/candidate/profile'
    | '/recruiter/dashboard'
    | '/recruiter/fingerprint'
    | '/recruiter/network'
    | '/recruiter/candidate/$candidateId'
    | '/recruiter/req/$reqId'
    | '/recruiter/req/new'
    | '/recruiter/req/$reqId/rerank'
  id:
    | '__root__'
    | '/'
    | '/candidate'
    | '/recruiter'
    | '/candidate/consent'
    | '/candidate/data'
    | '/candidate/login'
    | '/candidate/profile'
    | '/recruiter/dashboard'
    | '/recruiter/fingerprint'
    | '/recruiter/network'
    | '/recruiter/candidate/$candidateId'
    | '/recruiter/req/$reqId'
    | '/recruiter/req/new'
    | '/recruiter/req/$reqId_/rerank'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidateRoute: typeof CandidateRouteWithChildren
  RecruiterRoute: typeof RecruiterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/network': {
      id: '/recruiter/network'
      path: '/network'
      fullPath: '/recruiter/network'
      preLoaderRoute: typeof RecruiterNetworkRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/fingerprint': {
      id: '/recruiter/fingerprint'
      path: '/fingerprint'
      fullPath: '/recruiter/fingerprint'
      preLoaderRoute: typeof RecruiterFingerprintRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/dashboard': {
      id: '/recruiter/dashboard'
      path: '/dashboard'
      fullPath: '/recruiter/dashboard'
      preLoaderRoute: typeof RecruiterDashboardRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/login': {
      id: '/candidate/login'
      path: '/login'
      fullPath: '/candidate/login'
      preLoaderRoute: typeof CandidateLoginRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/data': {
      id: '/candidate/data'
      path: '/data'
      fullPath: '/candidate/data'
      preLoaderRoute: typeof CandidateDataRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/consent': {
      id: '/candidate/consent'
      path: '/consent'
      fullPath: '/candidate/consent'
      preLoaderRoute: typeof CandidateConsentRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/recruiter/req/new': {
      id: '/recruiter/req/new'
      path: '/req/new'
      fullPath: '/recruiter/req/new'
      preLoaderRoute: typeof RecruiterReqNewRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/req/$reqId': {
      id: '/recruiter/req/$reqId'
      path: '/req/$reqId'
      fullPath: '/recruiter/req/$reqId'
      preLoaderRoute: typeof RecruiterReqReqIdRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/candidate/$candidateId': {
      id: '/recruiter/candidate/$candidateId'
      path: '/candidate/$candidateId'
      fullPath: '/recruiter/candidate/$candidateId'
      preLoaderRoute: typeof RecruiterCandidateCandidateIdRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/req/$reqId_/rerank': {
      id: '/recruiter/req/$reqId_/rerank'
      path: '/req/$reqId/rerank'
      fullPath: '/recruiter/req/$reqId/rerank'
      preLoaderRoute: typeof RecruiterReqReqIdRerankRouteImport
      parentRoute: typeof RecruiterRoute
    }
  }
}

interface CandidateRouteChildren {
  CandidateConsentRoute: typeof CandidateConsentRoute
  CandidateDataRoute: typeof CandidateDataRoute
  CandidateLoginRoute: typeof CandidateLoginRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
}

const CandidateRouteChildren: CandidateRouteChildren = {
  CandidateConsentRoute: CandidateConsentRoute,
  CandidateDataRoute: CandidateDataRoute,
  CandidateLoginRoute: CandidateLoginRoute,
  CandidateProfileRoute: CandidateProfileRoute,
}

const CandidateRouteWithChildren = CandidateRoute._addFileChildren(
  CandidateRouteChildren,
)

interface RecruiterRouteChildren {
  RecruiterDashboardRoute: typeof RecruiterDashboardRoute
  RecruiterFingerprintRoute: typeof RecruiterFingerprintRoute
  RecruiterNetworkRoute: typeof RecruiterNetworkRoute
  RecruiterCandidateCandidateIdRoute: typeof RecruiterCandidateCandidateIdRoute
  RecruiterReqReqIdRoute: typeof RecruiterReqReqIdRoute
  RecruiterReqNewRoute: typeof RecruiterReqNewRoute
  RecruiterReqReqIdRerankRoute: typeof RecruiterReqReqIdRerankRoute
}

const RecruiterRouteChildren: RecruiterRouteChildren = {
  RecruiterDashboardRoute: RecruiterDashboardRoute,
  RecruiterFingerprintRoute: RecruiterFingerprintRoute,
  RecruiterNetworkRoute: RecruiterNetworkRoute,
  RecruiterCandidateCandidateIdRoute: RecruiterCandidateCandidateIdRoute,
  RecruiterReqReqIdRoute: RecruiterReqReqIdRoute,
  RecruiterReqNewRoute: RecruiterReqNewRoute,
  RecruiterReqReqIdRerankRoute: RecruiterReqReqIdRerankRoute,
}

const RecruiterRouteWithChildren = RecruiterRoute._addFileChildren(
  RecruiterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidateRoute: CandidateRouteWithChildren,
  RecruiterRoute: RecruiterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
